services:
  spring:
    container_name: spring
    image: spring:0.1
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
