server:
  port: 8080

spring:
  application:
    name: alcoholic

  messages:
    encoding: UTF-8

  profiles:
    active: prod

  jwt:
    secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

